version: '3.7'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["--strict.perms=false"]
    deploy:
      mode: global

